#include "exchange_data.h"

void exchange_data_display_as_currency(char *dest, int length, int value) {
    int32_t characteristic = 0;
    int32_t mantissa = 0;

    /* I know this looks like a lot of malarkey but the Pebble SDK is unable to
       unable to dispaly floating point values using format strings. The
       documentation specifically states that the %e, %f, and %f flags are not
       supported. To get around this limitation I had to jerryrig.

       The following code generates the characteristic (number in front of the
       decimal point) but doing integer division. The last two digits are
       truncated. After that the mantissa (number after the decimal point) is
       generated by subtracting the characteristic * 100 from the stored value.

       Feel free to laugh but it works.
    */
    characteristic = value / 100;
    mantissa = value - (characteristic * 100);
    snprintf(dest, length, "$ %ld.%02ld", characteristic, mantissa);
}

