#include "exchange.h"

void format_as_dollars(char *dest, int32_t value) {
    int32_t characteristic = 0;
    int32_t mantissa = 0;

    /* I know this looks like a lot of malarkey but the Pebble SDK is unable to
       unable to dispaly floating point values using format strings. The
       documentation specifically states that the %e, %f, and %f flags are not
       supported. To get around this limitation I had to jerryrig.

       The following code generates the characteristic (number in front of the
       decimal point) but doing integer division. The last two digits are
       truncated. After that the mantissa (number after the decimal point) is
       generated by subtracting the characteristic * 100 from the stored value.

       Feel free to laugh but it works.
    */
    characteristic = value / 100;
    mantissa = value - (characteristic * 100);
    snprintf(dest, PRICE_FIELD_LENGTH, "$ %ld.%02ld", characteristic, mantissa);
}

/*
void format_as_bitcoin_with_precision(char *dest, int64_t value, uint8_t precision) {
    int64_t characteristic = 0;
    int64_t mantissa = 0;    

    // Bitcoin can only be divided down to eight decimal points. Therefore any
    // precision higher than eight is useless.
    if (precision > 8) {
        precision = 8;
    }

    characteristic = value / 100000000;
    mantissa = value - (characteristic * 100000000);
    mantissa = mantissa / (10 ^ (8 - precision));

    snprintf(dest, VOLUME_FIELD_LENGTH, "%lld.%lld", characteristic, mantissa);
}

void format_as_bitcoin(char *dest, int64_t value) {
    format_as_bitcoin_with_precision(dest, value, 8);
}
*/

void format_as_bitcoin(char *dest, int64_t value) {
    int64_t characteristic = 0;
    int64_t mantissa = 0;    

    characteristic = value / 100000000;
    mantissa = value - (characteristic * 100000000);

    snprintf(dest, VOLUME_FIELD_LENGTH, "%lld.%08lld", characteristic, mantissa);
}

